# In this modified http-server we use a distroless python3 base-image from Google
FROM gcr.io/distroless/python3-debian12

WORKDIR /app

COPY html/* /app

EXPOSE 80

ENTRYPOINT ["python3", "-m", "http.server", "80"]

# If not defined, we inherit the ENTRYPOINT from base image
