services:
  ubuntu-debugger:
    build: ./1-ubuntu-debugger # Folder containing the Dockerfile, also known as the build context
    image: workshop/ubuntu-debugger # The name of the image to be built, in the format <repository>/<image-name>:<tag>

  java-app:
    build: ./2-java-hello-world
    image: workshop/java-hello-world

  java-pom-app:
    build: ./3-java-hello-world-pom
    image: workshop/java-hello-world-pom

  dotnet-app:
    build: ./4-dotnet-hello-world
    image: workshop/dotnet-hello-world
    environment:
      - DOTNET_ENVIRONMENT=Production

  static-web-app:
    build:
      context: ./5-static-web-app
      dockerfile: Dockerfile # Replace with Dockerfile-smaller if you want to use the smaller image
    image: workshop/static-web-app
    ports:
      - "127.0.0.1:8080:80"

  micro-go-app:
    build: ./edu-micro-go-app
    image: workshop/micro-go-app
