# In this modified http-server we use a distroless python3 base-image from Google
# :debug is a variant with "sh" shell available for debugging.
FROM gcr.io/distroless/python3-debian13:debug

WORKDIR /app

COPY html/* /app

EXPOSE 80

# Host our static website via Python's http.server.
ENTRYPOINT ["python3", "-m", "http.server", "80"]
