# Let's create a simple container that hosts a static HTML site via HTTP on a given port

# Pick an image that might help you run a HTTP server
FROM ...

# TODO: Copy in the `html/index.html` file and expose it via a HTTP server.

# TODO: Expose the port the HTTP server uses.

# TODO: Make an entrypoint that starts the http-server.
