# Let's create a simple container that hosts a static HTML site via HTTP on a given port

# Pick an image that might help you run a HTTP server
# Suggestions:
#   httpd python:3.12-slimhttpd#how-to-use-this-image
#   nignx https://hub.docker.com/_/nginx#how-to-use-this-image
FROM ...

# TODO: COPY in the 'html' folder to an appropriate location.

# TODO: EXPOSE the port the HTTP server uses.

# TODO: Make an ENTRYPOINT that starts the http-server.
