<!DOCTYPE HTML>
<html>
<head>
  <title>Getting Started: Serving Web Content</title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <style>body { margin: 40px; font-family: Roboto; font-size: 20px; }</style>
</head>
<body>
  <p>Hello from Spring Boot in ${name}!</p>
  <p>${body}</p>
  <h2>Other pages:</h2>
  <ul>
    <li><a href="/greetings">All greetings</a></li>
    <li><a href="/new">New greeting</a></li>
  </ul>
</body>
