FROM ubuntu:24.04

# TODO: install openjdk-21-jdk

# TODO: build the hello.java file with javac

COPY message.txt /data/message.txt

# TODO: Set the entrypoint to start the Hello.class

ENTRYPOINT ["java", "my-built-java-class"]
